site_settings.node_counter:
  version: VERSION
  css:
    theme:
      css/site_settings.css: {}
  js:
    js/site_settings.js: {}
  dependencies:
    - core/jquery
    - core/drupal
    - core/drupalSettings
    - core/once